### ISSUE TITLE
Wrong type annotation when using SQL arrays

### ISSUE THREAD

**Issue by Nereg** [rayakame/sqlc-gen-better-python#116]
I think the generator creates a wrong type annotation, when using SQL arrays. The queries still work fine, but the type annotation is wrong.
Here is my query:
```sql
-- name: test :many
SELECT * FROM test WHERE "Id" IN ($1);
```
which uses an SQL array with `IN` clause. Which generates this function: 
```py
def test(conn: ConnectionLike, *, Id: int) -> QueryResults[int]:
    """Fetch many from the db using the SQL query with `name: test :many`.

    Args:
        conn:
            Connection object of type `ConnectionLike` used to execute the query.
        Id: int.

    Returns:
        Helper class of type `QueryResults[int]` that allows both iteration and normal fetching of data from the db.
    """
    return QueryResults[int](conn, TEST, operator.itemgetter(0), Id)
```
where `Id` is just an `int` where it should be an int iterable. I also have debug logs, if you need them, and have this generator config:
```yaml
version: "2"
plugins:
  - name: python
    wasm:
      url: https://github.com/rayakame/sqlc-gen-better-python/releases/download/v0.4.3/sqlc-gen-better-python.wasm
      sha256: c178ef76085ab4737a9a83f1147662ff0a9a24b8513405880fdfcde3ad30ca66
sql:
  - engine: "postgresql" 
    queries: "test.sql"
    schema: "schema.sql"
    codegen:
      - out: .
        plugin: python
        options:
          package: .
          emit_init_file: false
          sql_driver: "asyncpg"
          docstrings: "google"
          emit_classes: false
          docstrings_emit_sql: false
          debug: true
```
The issue is small, but type hints are important. Feel free to ping me on discord, if you need!
