### ISSUE TITLE
Fix Missing empty lines when generating classes

### ISSUE THREAD

**Issue by rayakame** [rayakame/sqlc-gen-better-python#34]
Config to reproduce:
```yaml
version: "2"
plugins:
  - name: python
    wasm:
      url: file://sqlc-gen-better-python.wasm
      sha256: 453e3fbe37020527d1faf55a698e3019d30d46214c92b39837140d74d164a50d
sql:
  - schema: test/schema.sql
    queries: test/queries.sql
    engine: postgresql
    codegen:
      - out: test
        plugin: python
        options:
          package: test
          sql_driver: asyncpg
          model_type: dataclass
          emit_classes: true
          omit_unused_structs: true
```
